#%RAML 0.8
title: CurrentAirQualityInterfaceMapping
version: OCFv1.0.0-20170317
documentation:
  - title: (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - RetrieveSchema: !include asa.environment.currentairquality.json

traits:
  - interface-sensor:
      queryParameters:
        if:
          enum: ["oic.if.s","oic.if.baseline"]

/CurrentAirQualityResURI:
  description: |
    This API defines the mapping between the AllJoyn AirQuality interface and the OCF AirQuality Resource.
    If more than one instance of the AirQuality interface is exposed then each instance maps to an instance of the OCF AirQuality Resource.
    The mapping defined in the schema describes the population of the OCF AirQuality Resource.
    Even if there is only a single instance of an OCF AirQuality Resource this shall be included in an instance of an OCF AirQualityCollection.
    The number of links in the collection equates to the number of instances of the AllJoyn CurrentAirQuality interface that are exposed.
    When mapping from OCF the valueType of the Resource shall be introspected, this API is invoked only if this is set to 'Measured'

  displayName: Air Quality Mapping
  is: [ interface-sensor ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: RetrieveSchema
            example: |
              {
                "rt":     ["oic.r.airqualitycollection"]
              }
