#%RAML 0.8
title: FanSpeedLevelInterfaceMapping
version: OCFv1.0.0-20160701
documentation:
  - title: © 2017 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - RetrieveSchema: !include  asa.operation.fanspeedlevel.json
  - UpdateSchema: !include asa.operation.fanspeedlevel.json

traits:
  - interface-actuator:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.baseline"]

/FanSpeedLevelResURI:
  description: |
    This API defines the mapping between an instance of an ASA FanSpeedLevel interface and an OCF AirFlow Resource.
    Note that the setting of the FanSpeedLevel to '0x00' (off) is handled via the 'OffControl' interface rather than writing directly to this interface.
    In such a case an instance of Binary Switch shall be exposed on the OCF side; this can be modeled as AirFlowControl which is then a collection of Binary Switch and AirFlow.
  displayName: Fan Speed Level Mapping
  is: [ interface-actuator ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: RetrieveSchema
            example: |
              {
                "rt":     ["oic.r.airflow"]
              }

  post:
    body:
      application/json:
        schema: UpdateSchema
    responses:
      200:
        body:
          application/json:
            schema: UpdateSchema
